# Generated by Django 5.2.7 on 2025-10-05 02:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Spider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spider', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Scribble',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chat_history', models.JSONField(blank=True, default=list)),
                ('code', models.CharField(max_length=30000)),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scribblebug.spider')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('scribble', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scribblebug.scribble')),
                ('spider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scribblebug.spider')),
            ],
        ),
    ]
